### ISSUE TITLE
Drag and drop broken on firefox

### ISSUE THREAD

**Issue by RiahiKarim** [elsix/angular-jointjs-graph-demo#6]
Dragging and dropping an element in Firefox opens an invalid URL.

**Comment by npetkov** [comment]
Which OS and Firefox build are you using? Are you seeing some error in the console?

**Comment by RiahiKarim** [comment]
Thank you for your quick reply
![error](https://cloud.githubusercontent.com/assets/12436800/14761916/37d01fa0-0965-11e6-91fd-2a935d2a72c2.PNG)
OS : win 7 64 bit
Firefox : 45.0.2

**Comment by npetkov** [comment]
You're welcome. I'll post an update as soon as I have more insight into the problem.

**Comment by hisokader** [comment]
You need to prevent the event in the "dragEnd" and "drop" events
